Assignment questions


1. Create a null vector of size 10 but the fifth value which is 1

In [2]:
import numpy as np

In [6]:
array = np.zeros(10)
array[4] = 1
array

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

2. Create a vector with values ranging from 10 to 49.

In [11]:
arr = np.arange(10,50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

3. Create a 3x3 matrix with values ranging from 0 to 8

In [12]:
x =  np.arange(0, 9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [14]:
arr1 = [1,2,0,0,4,0]
arr2 = np.nonzero(arr1)
arr2

(array([0, 1, 4]),)

5. Create a 10x10 array with random values and find the minimum and maximum values.

In [29]:
x = np.random.randn(5,5)
print(f"minimum value is {x.min()}")
print(f"maximum value is {x.max()}")

minimum value is -2.1830219078969946
maximum value is 2.209318257028251


6. Create a random vector of size 30 and find the mean value.

In [27]:
v = np.random.random(30)
print(f" mean is {v.mean()}")

 mean is 0.40267674905692746
